language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install: 
  - pip install pybuilder
  - pyb install_dependencies
# command to run tests
script: 
  - pyb all_tests
env:
  - BOOKIT_USERNAME=username BOOKIT_PASSWORD=password
