language: python
python:
  - "3.6"
# command to install dependencies
install: 
  - pip install -r build-requirements.txt
  - pip install -r runtime-requirements.txt
# command to run tests
script: 
  - py.test
env:
  - BOOKIT_USERNAME=username
  - BOOKIT_PASSWORD=password
